packages:
  - 'apps/*'
  - 'packages/*'

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - msw
  - prisma
  - protobufjs
  - sharp
  - unrs-resolver
